USE jobster_db;

INSERT INTO applicants (firstName, lastName, email, phone, password, linkedIn, personalUrl, videoUrl, availability, zipcode, salary, jobtitle, createdAt, updatedAt) VALUES ('Tony', 'Dupone', 'tdupone@example.com', '555-666-7777', 'password', 'linkedinthingie','websitethingie','assets/images/profile1.jpg',  01/01/2019, '30318', '12', 'Waiter', NOW(), NOW());
INSERT INTO applicants (firstName, lastName, email, phone, password, linkedIn, personalUrl, videoUrl, availability, zipcode, salary, jobtitle, createdAt, updatedAt) VALUES ('Bob', 'Brown', 'bbrown@example.com', '555-666-7777', 'password', 'linkedinthingie','websitethingie','assets/images/profile14.jpg',  01/01/2019, '30318', '12', 'Waiter', NOW(), NOW());
INSERT INTO applicants (firstName, lastName, email, phone, password, linkedIn, personalUrl, videoUrl, availability, zipcode, salary, jobtitle, createdAt, updatedAt) VALUES ('Konstantin', 'Filippov', 'kflippov@example.com', '555-666-7777', 'password', 'linkedinthingie','websitethingie','assets/images/profile2.jpg',  02/02/2019, '30318', '8','Waiter', NOW(), NOW());
INSERT INTO applicants (firstName, lastName, email, phone, password, linkedIn, personalUrl, videoUrl, availability, zipcode, salary, jobtitle, createdAt, updatedAt) VALUES ('Kharen', 'Yao', 'kyao@example.com', '555-666-7777', 'password', 'linkedinthingie','websitethingie','assets/images/profile12.jpg',  03/03/2019, '30318', '10', 'Waiter', NOW(), NOW());
INSERT INTO applicants (firstName, lastName, email, phone, password, linkedIn, personalUrl, videoUrl, availability, zipcode, salary, jobtitle, createdAt, updatedAt) VALUES ('Maxim', 'Gurbanov', 'mgurbanov@example.com', '555-666-7777', 'password', 'linkedinthingie','websitethingie','assets/images/profile9.jpg',  01/15/2019, '30318', '8', 'Waiter', NOW(), NOW());
INSERT INTO applicants (firstName, lastName, email, phone, password, linkedIn, personalUrl, videoUrl, availability, zipcode, salary, jobtitle, createdAt, updatedAt) VALUES ('Erwin', 'Garcia', 'egarcia@example.com', '555-666-7777', 'password', 'linkedinthingie','websitethingie','assets/images/profile10.jpg',  02/15/2019, '30318', '8', 'Waiter', NOW(), NOW());
INSERT INTO applicants (firstName, lastName, email, phone, password, linkedIn, personalUrl, videoUrl, availability, zipcode, salary, jobtitle, createdAt, updatedAt) VALUES ('Jennifer', 'Antoneythansan', 'jantoneythasan@example.com','555-666-7777', 'password', 'linkedinthingie','websitethingie','assets/images/profile6.jpg',  03/15/2019, '30318', '8', 'Waiter', NOW(), NOW());
INSERT INTO applicants (firstName, lastName, email, phone, password, linkedIn, personalUrl, videoUrl, availability, zipcode, salary, jobtitle, createdAt, updatedAt) VALUES ('Rachel', 'Urbelis', 'rurbelis@example.com', '555-666-7777', 'password', 'linkedinthingie','websitethingie','assets/images/profile8.jpg',  03/03/2019, '30318', '8', 'Waiter', NOW(), NOW());
INSERT INTO applicants (firstName, lastName, email, phone, password, linkedIn, personalUrl, videoUrl, availability, zipcode, salary, jobtitle, createdAt, updatedAt) VALUES ('Nur', 'Sazali', 'nsazali@example.com', '555-666-7777', 'password','linkedinthingie','websitethingie','assets/images/profile4.jpg',  03/03/2019, '30318', '8', 'Waiter', NOW(), NOW());



