USE jobster_db;

INSERT INTO applicants (username, password, firstName, lastName, email, phone, linkedIn, personalUrl, videoUrl, availability, zipcode, salary, jobtitle, createdAt, updatedAt) VALUES ('username','password','Tony', 'Dupone', 'tdupone@example.com', '555-666-7777', 'linkedinthingie','websitethingie','assets/images/profile1.jpg',  01/01/2019, '30318', '12', 'Waiter', NOW(), NOW());
INSERT INTO applicants (username, password, firstName, lastName, email, phone, linkedIn, personalUrl, videoUrl, availability, zipcode, salary, jobtitle, createdAt, updatedAt) VALUES ('username','password','Konstantin', 'Filippov', 'tdupone@example.com', '555-666-7777', 'linkedinthingie','websitethingie','assets/images/profile2.jpg',  01/01/2019, '30318', '12', 'Waiter', NOW(), NOW());
INSERT INTO applicants (username, password, firstName, lastName, email, phone, linkedIn, personalUrl, videoUrl, availability, zipcode, salary, jobtitle, createdAt, updatedAt) VALUES ('username','password','Kharen', 'Yao', 'tdupone@example.com', '555-666-7777', 'linkedinthingie','websitethingie','assets/images/profile12.jpg',  01/01/2019, '30318', '12', 'Waiter', NOW(), NOW());
INSERT INTO applicants (username, password, firstName, lastName, email, phone, linkedIn, personalUrl, videoUrl, availability, zipcode, salary, jobtitle, createdAt, updatedAt) VALUES ('username','password','Maxim', 'Gurbanov', 'tdupone@example.com', '555-666-7777', 'linkedinthingie','websitethingie','assets/images/profile9.jpg',  01/01/2019, '30318', '12', 'Waiter', NOW(), NOW());
INSERT INTO applicants (username, password, firstName, lastName, email, phone, linkedIn, personalUrl, videoUrl, availability, zipcode, salary, jobtitle, createdAt, updatedAt) VALUES ('username','password','Erwin', 'Garcia', 'tdupone@example.com', '555-666-7777', 'linkedinthingie','websitethingie','assets/images/profile10.jpg',  01/01/2019, '30318', '12', 'Waiter', NOW(), NOW());
INSERT INTO applicants (username, password, firstName, lastName, email, phone, linkedIn, personalUrl, videoUrl, availability, zipcode, salary, jobtitle, createdAt, updatedAt) VALUES ('username','password','Jennifer', 'Anthoneythansan', 'tdupone@example.com', '555-666-7777', 'linkedinthingie','websitethingie','assets/images/profile6.jpg',  01/01/2019, '30318', '12', 'Waiter', NOW(), NOW());
INSERT INTO applicants (username, password, firstName, lastName, email, phone, linkedIn, personalUrl, videoUrl, availability, zipcode, salary, jobtitle, createdAt, updatedAt) VALUES ('username','password','Rachel', 'Urbelis', 'tdupone@example.com', '555-666-7777', 'linkedinthingie','websitethingie','assets/images/profile8.jpg',  01/01/2019, '30318', '12', 'Waiter', NOW(), NOW());
INSERT INTO applicants (username, password, firstName, lastName, email, phone, linkedIn, personalUrl, videoUrl, availability, zipcode, salary, jobtitle, createdAt, updatedAt) VALUES ('username','password','Nur', 'Sazaki', 'tdupone@example.com', '555-666-7777', 'linkedinthingie','websitethingie','assets/images/profile4.jpg',  01/01/2019, '30318', '12', 'Waiter', NOW(), NOW());

